name: CI

on:
  push:
    branches:
      - main
      - next
  pull_request:
  merge_group:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Check Build
        run: pnpm build

      - name: Run tests
        run: pnpm test:only

      - name: Linting
        run: pnpm lint

      - name: Format package.json
        run: |
          pnpm biome format --write ./packages/traverse-files/package.json
          pnpm biome format --write ./packages/workspace/package.json
          pnpm biome format --write ./packages/workspace-node/package.json
          pnpm biome format --write ./packages/slimfast/package.json
          pnpm biome format --write ./packages/slimfast-node/package.json
          pnpm biome format --write ./config/tsconfig/package.json

      - name: Check Format
        run: pnpm check:format
